-- Run once before using the user API. Transaction rolls back on any failure.
BEGIN;
LOCK TABLE public."User" IN ACCESS EXCLUSIVE MODE;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public."User"
        WHERE cardinality("First Name") > 1 OR cardinality("Last Name") > 1
           OR cardinality("Username") > 1 OR cardinality("Password_Hash") > 1
           OR cardinality("Password_Salt") > 1
    ) THEN
        RAISE EXCEPTION 'User contains multi-value fields; manual migration required';
    END IF;
END $$;
ALTER TABLE public."User"
    ALTER COLUMN "First Name" TYPE text USING ("First Name")[array_lower("First Name", 1)],
    ALTER COLUMN "Last Name" TYPE text USING ("Last Name")[array_lower("Last Name", 1)],
    ALTER COLUMN "Username" TYPE text USING ("Username")[array_lower("Username", 1)],
    ALTER COLUMN "Password_Hash" TYPE text USING ("Password_Hash")[array_lower("Password_Hash", 1)],
    ALTER COLUMN "Password_Salt" TYPE text USING ("Password_Salt")[array_lower("Password_Salt", 1)],
    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public."User"', 'Id'),
    GREATEST(COALESCE((SELECT MAX("Id") FROM public."User"), 0) + 1, 1), false);
CREATE UNIQUE INDEX user_username_unique ON public."User" (lower("Username"));
COMMIT;
