BEGIN;
LOCK TABLE public."Form" IN ACCESS EXCLUSIVE MODE;
ALTER TABLE public."Form" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('public."Form"', 'Id'),
    GREATEST(COALESCE((SELECT MAX("Id") FROM public."Form"), 0) + 1, 1), false);
COMMIT;
