BEGIN;
LOCK TABLE public."Questions" IN ACCESS EXCLUSIVE MODE;
ALTER TABLE public."Questions"
    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN "Key" text;
SELECT setval(pg_get_serial_sequence('public."Questions"', 'Id'),
    GREATEST(COALESCE((SELECT MAX("Id") FROM public."Questions"), 0) + 1, 1), false);
CREATE UNIQUE INDEX questions_form_key_unique ON public."Questions" ("Form", "Key");
COMMIT;
