--
-- PostgreSQL database dump
--

\restrict Vi3sK5C3P5LBD3XYbYdD9V9vn9sSZYTY8SEV3h35v9qXmxabMmCjpdDF0FTBaeM

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Colors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Colors" (
    "Id" integer NOT NULL,
    "Name" character varying(255)
);


ALTER TABLE public."Colors" OWNER TO postgres;

--
-- Name: Colors_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Colors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Colors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Feedback" (
    "Id" integer NOT NULL,
    "Choice" character varying(255)
);


ALTER TABLE public."Feedback" OWNER TO postgres;

--
-- Name: Form; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Form" (
    "Id" integer NOT NULL,
    "User" integer,
    "Date_Created" date,
    "Status_Id" integer
);


ALTER TABLE public."Form" OWNER TO postgres;

--
-- Name: Form_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Form" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Form_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Inconveniences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Inconveniences" (
    "Id" integer NOT NULL,
    "Name" character varying(255)
);


ALTER TABLE public."Inconveniences" OWNER TO postgres;

--
-- Name: Questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Questions" (
    "Id" integer NOT NULL,
    "Form" integer,
    "Question" character varying,
    "Answer" character varying,
    "Key" text
);


ALTER TABLE public."Questions" OWNER TO postgres;

--
-- Name: Questions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Questions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Questions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Status" (
    "Id" integer NOT NULL,
    "Status" character varying
);


ALTER TABLE public."Status" OWNER TO postgres;

--
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    "Id" integer NOT NULL,
    "First Name" text,
    "Last Name" text,
    "Username" text,
    "Password_Hash" text,
    "Password_Salt" text
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- Name: User_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revoked_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.revoked_tokens (
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


ALTER TABLE public.revoked_tokens OWNER TO postgres;

--
-- Data for Name: Colors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Colors" ("Id", "Name") FROM stdin;
1	Firetruck Red
2	Smashed Pumpkin
3	Macaroni and Cheese
4	Granny Smith Apple
5	Sky at 3pm
6	Grape Juice
7	Cotton Candy
8	Ghost
9	Mud
10	Asphalt
\.


--
-- Data for Name: Feedback; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Feedback" ("Id", "Choice") FROM stdin;
1	Absolutely!
2	Meh!
3	Neutral
4	Meh.
5	Not at all! A waste of time and other negative words!
\.


--
-- Data for Name: Form; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Form" ("Id", "User", "Date_Created", "Status_Id") FROM stdin;
16	9	2026-09-18	3
3	3	2026-09-18	3
18	10	2026-09-18	3
14	8	2026-09-18	3
\.


--
-- Data for Name: Inconveniences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Inconveniences" ("Id", "Name") FROM stdin;
1	Traffic
2	Mosquitos
3	Slow Wi-Fi
4	Long lines
5	Spam calls
6	Missing socks
\.


--
-- Data for Name: Questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Questions" ("Id", "Form", "Question", "Answer", "Key") FROM stdin;
29	3	What is your favorite color?	Grape Juice	color
30	3	Are pineapples on pizza acceptable?	No	firstSurvey
31	3	Would you rather have…	Waffles for Ears	wouldRather
32	3	What animal would be the worst roommate?	Elephant	animalRoommate
33	3	How many tacos could you eat in one sitting?	3	tacoCount
34	3	Which minor inconvenience would you eliminate forever?	Mosquitos	incon
35	3	How would you rate this survey?	Not at all! A waste of time and other negative words!	feedback
71	18	What is your favorite color?	Sky at 3pm	color
72	18	Are pineapples on pizza acceptable?	No	firstSurvey
73	18	Would you rather have…	Spaghetti for Hair	wouldRather
74	18	What animal would be the worst roommate?	\N	animalRoommate
75	18	How many tacos could you eat in one sitting?	\N	tacoCount
76	18	Which minor inconvenience would you eliminate forever?	Slow Wi-Fi	incon
77	18	How would you rate this survey?	Absolutely!	feedback
57	16	What is your favorite color?	Granny Smith Apple	color
58	16	Are pineapples on pizza acceptable?	No	firstSurvey
59	16	Would you rather have…	Spaghetti for Hair	wouldRather
60	16	What animal would be the worst roommate?	dog	animalRoommate
61	16	How many tacos could you eat in one sitting?	4	tacoCount
62	16	Which minor inconvenience would you eliminate forever?	Traffic	incon
63	16	How would you rate this survey?	Meh.	feedback
43	14	What is your favorite color?	Smashed Pumpkin	color
44	14	Are pineapples on pizza acceptable?	No	firstSurvey
45	14	Would you rather have…	Spaghetti for Hair	wouldRather
46	14	What animal would be the worst roommate?	Dragon	animalRoommate
47	14	How many tacos could you eat in one sitting?	17	tacoCount
48	14	Which minor inconvenience would you eliminate forever?	Missing socks	incon
49	14	How would you rate this survey?	Absolutely!	feedback
\.


--
-- Data for Name: Status; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Status" ("Id", "Status") FROM stdin;
3	Completed
2	In Progress
1	Initialized
\.


--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" ("Id", "First Name", "Last Name", "Username", "Password_Hash", "Password_Salt") FROM stdin;
3	Frodo	Baggins	One_Ring	$argon2id$v=19$m=65536,p=1,t=3$Am0iPskDNnOAxAFe+ACF7g$Vgq2aPDOQ/Ioj9Ht2JFs9hOS7csSpahIKY2kXgF3rgA	Am0iPskDNnOAxAFe+ACF7g==
8	Luke	Skywalker	BlueSaber	$argon2id$v=19$m=65536,p=1,t=3$5VSa+NXUDhVeUEA3f9RdsA$sSzg8c6AdTGpCuexfjBPppK7Z+oz6ZPAg2N8+y/oHxs	5VSa+NXUDhVeUEA3f9RdsA==
9	mikky	mouse	mikky9	$argon2id$v=19$m=65536,p=1,t=3$rYt4FNvmS3yF6Yzo9TcKpg$H2qBJrfFOWUTI6PuuBqdFisLxw49C3ZL2tJqNBeTOB4	rYt4FNvmS3yF6Yzo9TcKpg==
10	ram	parvatini	ramparvatini@gmail.com	$argon2id$v=19$m=65536,p=1,t=3$9fnSI/tyUwApSKJkG5+3PA$QuCN30Thr11z/tvA873LU4MGDPZ0RWwQZlxXzeVQ1KE	9fnSI/tyUwApSKJkG5+3PA==
\.


--
-- Data for Name: revoked_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.revoked_tokens (token_hash, expires_at) FROM stdin;
\.


--
-- Name: Colors_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Colors_Id_seq"', 10, true);


--
-- Name: Form_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Form_Id_seq"', 34, true);


--
-- Name: Questions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Questions_Id_seq"', 189, true);


--
-- Name: User_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_Id_seq"', 11, true);


--
-- Name: Colors Colors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Colors"
    ADD CONSTRAINT "Colors_pkey" PRIMARY KEY ("Id");


--
-- Name: Feedback Feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Feedback"
    ADD CONSTRAINT "Feedback_pkey" PRIMARY KEY ("Id");


--
-- Name: Form Form_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Form"
    ADD CONSTRAINT "Form_pkey" PRIMARY KEY ("Id");


--
-- Name: Inconveniences Inconveniences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Inconveniences"
    ADD CONSTRAINT "Inconveniences_pkey" PRIMARY KEY ("Id");


--
-- Name: Questions Questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "Questions_pkey" PRIMARY KEY ("Id");


--
-- Name: Status Status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Status"
    ADD CONSTRAINT "Status_pkey" PRIMARY KEY ("Id");


--
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("Id");


--
-- Name: revoked_tokens revoked_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.revoked_tokens
    ADD CONSTRAINT revoked_tokens_pkey PRIMARY KEY (token_hash);


--
-- Name: Form userId; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Form"
    ADD CONSTRAINT "userId" UNIQUE ("User");


--
-- Name: questions_form_key_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX questions_form_key_unique ON public."Questions" USING btree ("Form", "Key");


--
-- Name: revoked_tokens_expiry; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX revoked_tokens_expiry ON public.revoked_tokens USING btree (expires_at);


--
-- Name: user_username_unique; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX user_username_unique ON public."User" USING btree (lower("Username"));


--
-- Name: Questions Form_Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "Form_Id" FOREIGN KEY ("Form") REFERENCES public."Form"("Id");


--
-- Name: Form Status_Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Form"
    ADD CONSTRAINT "Status_Id" FOREIGN KEY ("Status_Id") REFERENCES public."Status"("Id") NOT VALID;


--
-- Name: Form User_Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Form"
    ADD CONSTRAINT "User_Id" FOREIGN KEY ("User") REFERENCES public."User"("Id");


--
-- PostgreSQL database dump complete
--

\unrestrict Vi3sK5C3P5LBD3XYbYdD9V9vn9sSZYTY8SEV3h35v9qXmxabMmCjpdDF0FTBaeM

